hydra:  
  output_subdir: null  
  run:  
    dir: .
    
defaults:
  - process: process_2
  - segment: KMeans
  - _self_

raw_data: 
  path: data/raw/marketing_campaign.csv

data: 
  raw: raw
  intermediate: scale_features
  segmented: segmented

connection:
  user: postgres
  password: 123456
  host: localhost:5432
  database: customer_segmentation
  
flow: all 

pca:
  n_components: 3
  columns:
  - col1
  - col2
  - col3

elbow_metric: silhouette

image:
  elbow: image/elbow.png
  clusters: image/cluster.png

wandb_mode: 